services:
  - type: web
    name: qzfi
    env: node
    plan: free
    buildCommand: npm install && npm ci
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
